# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main", "dev", "release/*" ]
  pull_request:
    branches: [ "main", "dev", "release/*" ]


jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          preferLatestVersion: true
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
      - name: Show version
        run: echo $GitVersion_FullSemVer
      - id: step1
        run: echo test=$GitVersion_FullSemVer >> "GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
          
  build:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Show Version
      env:
        OUTPUT1: ${{ needs.versioning.outputs.output1 }}
        OUTPUT2: ${{ needs.versioning.outputs.output2 }}
      run: echo $OUTPUT1 $OUTPUT2
