# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: versioning

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Git Version
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main
          dev-branch: dev
          prefix: v
          log-paths: ./
      
